var cronograma = [
{
"predio": "P01",
"sala": "BANHEIRO PLASTICO - M",
"turno": "T1, T2, T3",
"rota": "01, 01, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P01",
"sala": "BANHEIRO VIRABREQUIM - M",
"turno": "T1, T2, T3",
"rota": "01, 01, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P01",
"sala": "BANHEIRO VIRABREQUIM - M",
"turno": "T1, T2, T3",
"rota": "01, 01, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P01",
"sala": "BANHEIRO VIRABREQUIM - F",
"turno": "T1, T2, T3",
"rota": "01, 01, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P01",
"sala": "SALA MONTAGEM BOMBA DE OLEO",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA QUARENTENA",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA SUPERVISAO VIRABREQUIM",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "MULTIMEC - SALA LOGISTICA",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "MULTIMEC - SALA ADM",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "MULTIMEC - SALA ADM 2",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "JURIDICO - SALA ADM",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "JURIDICO - SALA ESPECIALISTA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA CENTRAL DE MANUTENCAO MOTORES",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA METROLOGIA TRIDIMENSIONAL",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA METROLOGIA VIRABREQUIM",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "TRF - SALA ADM",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA IMPRESSAO DE ETIQUETAS",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA SUPERVISAO MANUTENCAO",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "TRF - SALA REUNIAO I",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA LABORATORIO PLASTICO",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "TRF - SALA OFICINA",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA PRE AUDITORIA MONTAGEM",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "SALA TRF MOTORES - DISPOSITIVOS",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "JURIDICO - SALA GERENCIA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P01",
"sala": "JURIDICO - COPA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P02",
"sala": "BANHEIRO PORTARIA 1 - VIGILANTES",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P02",
"sala": "BANHEIRO PORTARIA 1 - RECEPCAO",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P02",
"sala": "SALA DE ESPERA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P02",
"sala": "SALA RECEPCAO",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "BANHEIRO ATI - M",
"turno": "T2, T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "BANHEIRO ATI - F",
"turno": "T2, T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "HALL DE ENTRADA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA GERENCIA ATI",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA REUNIAO SISTEMAS",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA ADM SISTEMAS",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA MONITORAMENTO",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA HELPDESK",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA REUNIAO INFRAESTRUTURA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "COPA",
"turno": "T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P03",
"sala": "SALA INFRAESTRUTURA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "BANHEIRO FINANCEIRO - M",
"turno": "T2, T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "BANHEIRO FINANCEIRO - F",
"turno": "T2, T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "BANHEIRO FINANCEIRO - C",
"turno": "T2, T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "HALL DE ENTRADA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "CONTABILIDADE - SALA REUNIAO I",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "CONTROLADORIA - SALA REUNIAO II",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "FINANCEIRO - SALA GERENCIA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "CONTABILIDADE - SALA GERENCIA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "JURIDICO - SALA ADM",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "CONTROLADORIA - SALA ADM",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "FINANCEIRO / CONTABILIDADE - SALA ADM",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "COPA",
"turno": "T3",
"rota": "01, 02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P04",
"sala": "CONTROLADORIA - SALA GERENCIA",
"turno": "T3",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P07",
"sala": "BANHEIRO ALMOXARIFADO - M",
"turno": "T2, T3",
"rota": "01, 13", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P07",
"sala": "LOGISTICA - SALA ADM",
"turno": "T3",
"rota": "13", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P07",
"sala": "MANSERV - SALA ADM",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P07",
"sala": "FASTENAL - SALA ADM",
"turno": "T3",
"rota": "13", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P07",
"sala": "MANSERV - SALA REUNIAO I",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P07",
"sala": "TRANSPOTECH - OFICINA",
"turno": "T2",
"rota": "01", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "BANHEIRO CENTRAL QUALIDADE - M",
"turno": "T3",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P11",
"sala": "BANHEIRO CENTRAL QUALIDADE - F",
"turno": "T3",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P11",
"sala": "BANHEIRO FUNDICAO GRAVIDADE - M",
"turno": "T1, T2, T3",
"rota": "01, 02, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "BANHEIRO FUNDICAO GRAVIDADE - F",
"turno": "T1, T2, T3",
"rota": "01, 02, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "BANHEIRO MELHORIA CONTINUA - M",
"turno": "T2",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P11",
"sala": "BANHEIRO MELHORIA CONTINUA - F",
"turno": "T2",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P11",
"sala": "ESCADARIA HALL PEO",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "ESCADARIA HALL PQA",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "PEO - SALA EXCELENCIA OPERACIONAL",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "PEO - SALA GERENCIA",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "CENTRAL QUALIDADE - SALA ADM",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA FERRAMENTARIA ZFG",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "CENTRAL QUALIDADE - COPA",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO MATERIAIS QUIMICOS I",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO METALURGICO",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "CENTRAL QUALIDADE - SALA REUNIAO I",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA SUPERVISAO GRAVIDADE",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "CENTRAL QUALIDADE - GERENCIA",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SEP - SALA ADM",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "INHAUS - SALA ADM",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO MATERIAIS / INSTRUMENT",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO MATERIAIS QUIMICOS II",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA AUDITORIA",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO MECANICA FINA",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO CALIBRACAO",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO HIDRAULICA",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "INHAUS - SALA COORDENACAO",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO ELETRONICA E CALIBRACAO",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA LABORATORIO ZFG",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA QUALIDADE / LABORATORIO - MEZANINO",
"turno": "T3",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "PEO - SALA KAIZEN I",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "PEO - SALA KAIZEN II",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "SALA ENGENHARIA PROCESSOS",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P11",
"sala": "PEO - COPA",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO PORTARIA 2 - VIGILANTES",
"turno": "T2",
"rota": "03, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO PORTARIA 2 - RECEPCAO",
"turno": "T2",
"rota": "03, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO PORTARIA 2 - C",
"turno": "T2",
"rota": "03, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO LOGISTICA - M",
"turno": "T2,T3",
"rota": "03, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO LOGISTICA - F",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO TREINAMENTOS - M",
"turno": "T2, T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "BANHEIRO TREINAMENTOS - F",
"turno": "T2, T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "LOGISTICA - SALA ADM",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "LOGISTICA - SALA REUNIAO I",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "PORTARIA 2 - SALA RECEPCAO",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "PORTARIA 2 - SALA RECEBIMENTO FISCAL",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "PORTARIA 2 - SALA DE ESPERA",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "LOGISTICA - SALA SUPERVISAO",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "SALA GUICHE ALMOXARIFADO",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "PQR - SALA LABORATORIO DIMENSIONAL",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "SALA BRIGADA DE EMERGENCIA",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "PQR - SALA ADM",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "LOGISTICA - RECEBIMENTO",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "PQR - SALA REUNIAO I",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "LOGISTICA - COPA",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "SALA SPCI",
"turno": "T2",
"rota": "03", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P16",
"sala": "BANHEIRO SABRES - M",
"turno": "T1, T2, T3",
"rota": "01, 04, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P16",
"sala": "BANHEIRO AUDITORIO - F",
"turno": "SOB DEMANDA",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P16",
"sala": "BANHEIRO AUDITORIO - M",
"turno": "SOB DEMANDA",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P16",
"sala": "ESCADARIA AUDITORIO",
"turno": "SOB DEMANDA",
"rota": "", 
"dom": "X",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P16",
"sala": "AUDITORIO",
"turno": "SOB DEMANDA",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P16",
"sala": "SALA SUPERVISAO SABRES",
"turno": "T2",
"rota": "04", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P16",
"sala": "SALA LABORATORIO METALURGICO",
"turno": "T2",
"rota": "04", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P16",
"sala": "SALA TRF SABRES",
"turno": "T2",
"rota": "04", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P16",
"sala": "HALL AUDITORIO",
"turno": "SOB DEMANDA",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P18",
"sala": "BANHEIRO COMPRAS / PLANEJ - M",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "BANHEIRO COMPRAS / PLANEJ - F",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "BANHEIRO PRESIDENCIA - M",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "BANHEIRO PRESIDENCIA - F",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "ESCADARIA DIRETORIA",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - HALL DE ENTRADA",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - SALA VP OPERACOES",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - SALA REUNIAO II VIDEOCONF",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - SALA PRESIDENTE",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - SALA VP MARKETING",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - SALA VP FINANCAS",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - SALA REUNIAO I",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "COMPRAS - SALA REUNIAO II",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P18",
"sala": "COMPRAS - SALA ADM",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "COMPRAS - SALA REUNIAO I",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P18",
"sala": "COMPRAS - SALA GERENCIA COMPRAS",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P18",
"sala": "COMPRAS - SALA GERENCIA SUPPLY CHAIN",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P18",
"sala": "PRESIDENCIA - COPA",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "COMPRAS - COPA",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P18",
"sala": "HALL DE ENTRADA",
"turno": "T2",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P20",
"sala": "BANHEIRO AFAS GALPAO - M",
"turno": "SOB DEMANDA",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P20",
"sala": "BANHEIRO AFAS GALPAO - F",
"turno": "SOB DEMANDA",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P20",
"sala": "COZINHA / CHURRASQUEIRA",
"turno": "SOB DEMANDA",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P20",
"sala": "SALA DE AUDIO E VIDEO",
"turno": "SOB DEMANDA",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P20",
"sala": "GALPAO PRINCIPAL",
"turno": "SOB DEMANDA",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P20",
"sala": "CORREDOR",
"turno": "SOB DEMANDA",
"rota": "05", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P26",
"sala": "BANHEIRO CENTRAL DE RESIDUOS - M",
"turno": "T2, T3",
"rota": "01, 13", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P26",
"sala": "CENTRAL DE RESIDUOS - SALA ADM",
"turno": "T3",
"rota": "13", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "BANHEIRO COZINHA - M",
"turno": "T3",
"rota": "01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "BANHEIRO COZINHA - USO COMUM",
"turno": "T3",
"rota": "01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "BANHEIRO CENTRAL DE SERVICOS - M",
"turno": "T1, T2, T3",
"rota": "04, 02, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "BANHEIRO CENTRAL DE SERVICOS - F",
"turno": "T1, T2, T3",
"rota": "04, 02, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "BANHEIRO AMBULATORIO - USO COMUM",
"turno": "T2, T3",
"rota": "02, 01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "ESCADARIAS RESTAURANTE (ADICIONADO)",
"turno": "T2",
"rota": "04, 02", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P27",
"sala": "RESTAURANTE",
"turno": "T1, T2, T3",
"rota": "04, 06, 05", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "AGENCIA BANCARIA",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - HALL DE ENTRADA",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - SALA PROCEDIMENTOS I",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - AUDIOMETRIA",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - SALA ENFERMEIRAS II",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - SALA ENFERMEIRAS I",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - CONSULTORIO MEDICO I",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - CONSULTORIO MEDICO II",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - CONSULTORIO MEDICO III",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "CENTRAL DE SERVICOS - LOJA STIHL",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P27",
"sala": "AGENCIA BANCARIA - GERENCIA",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - SALA PROCEDIMENTOS II",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "CENTRAL DE SERVICOS",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "CENTRAL DE SERVICOS - LANCHERIA",
"turno": "T2",
"rota": "02", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - COPA",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P27",
"sala": "AMBULATORIO - CORREDOR",
"turno": "T2",
"rota": "02", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO FUNDICAO ALUMINIO - M",
"turno": "T1, T2, T3",
"rota": "02, 07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO FUNDICAO ALUMINIO - F",
"turno": "T1, T2, T3",
"rota": "02, 07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO ADM CILINDROS OESTE - M",
"turno": "T2,T3",
"rota": "07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO ADM CILINDROS OESTE - F",
"turno": "T2, T3",
"rota": "07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO USINAGEM CILINDROS - M",
"turno": "T1, T2, T3",
"rota": "02, 07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO USINAGEM CILINDROS - F",
"turno": "T1, T2, T3",
"rota": "02, 07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO ADM CILINDROS LESTE - M",
"turno": "T2,T3",
"rota": "07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "BANHEIRO ADM CILINDROS LESTE - F",
"turno": "T2, T3",
"rota": "07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - ESCADARIA OESTE",
"turno": "T2",
"rota": "07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - ESCADARIA LESTE",
"turno": "T2",
"rota": "07, 16", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P28",
"sala": "SALA METROTOM",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA METROLOGIA TRIDIMENSIONAL",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA QUALIDADE METROLOGIA",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA METROLOGIA CALIBRACAO",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA CENTRAL RAIO X",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA TRF - USINAGEM PRESET FERRAMENTAS",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA REUNIAO ZUC",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA ADM",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA TRF - FUNDICAO PREP FERRAMENTAS",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA ESTOQUE DE INSTRUMENTOS",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA SUPERVISAO ZFA",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA MANUTENCAO MINI FABRICA USINAGEM",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA TECNICOS MANUTENCAO",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - COPA",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA GERENCIA I",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA GERENCIA II",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA GERENCIA III",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P28",
"sala": "ADM CILINDROS - SALA GERENCIA IV",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA FERRAMENTARIA",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P28",
"sala": "SALA PREPARADOR",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P29",
"sala": "BANHEIRO CQS - M",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "BANHEIRO CQS - F",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "MUSEU",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SALA DE TREINAMENTO I - SOPRADOR",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SALA DE TREINAMENTO II - PERFURADOR",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SHOWROOM",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SALA DE MAQUINAS",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SALA INSTRUTORES 1",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SALA INSTRUTORES 2",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "SALA OFICINA",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "HALL DE ENTRADA",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "REALIDADE VIRTUAL",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P29",
"sala": "CORREDOR",
"turno": "T2",
"rota": "", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO FUNDICAO MAGNESIO - M",
"turno": "T1, T2, T3",
"rota": "02, 08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO FUNDICAO MAGNESIO - F",
"turno": "T1, T2, T3",
"rota": "02, 08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG FERRAMENTARIA 2o PISO - M",
"turno": "T3",
"rota": "06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG FERRAMENTARIA 2o PISO - F",
"turno": "T3",
"rota": "06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG MANUTENCAO 3o PISO - M",
"turno": "T3",
"rota": "06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG MANUTENCAO 3o PISO - F",
"turno": "T3",
"rota": "06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO BRUNIMENTO SUL - M",
"turno": "T1, T2, T3",
"rota": "02, 08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO BRUNIMENTO SUL - F",
"turno": "T1, T2, T3",
"rota": "02, 08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO BRUNIMENTO NORTE - M",
"turno": "T1, T2, T3",
"rota": "02, 08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO BRUNIMENTO NORTE - F",
"turno": "T1, T2, T3",
"rota": "02, 08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO TREINAMENTOS 2o PISO SUL - M",
"turno": "T2, T3",
"rota": "08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO TREINAMENTOS 2o PISO SUL - F",
"turno": "T2, T3",
"rota": "08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO TREINAMENTOS 2o PISO NORTE - M",
"turno": "T2, T3",
"rota": "08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO TREINAMENTOS 2o PISO NORTE - F",
"turno": "T2, T3",
"rota": "08, 06", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG CILINDROS 3o PISO SUL - M",
"turno": "T2",
"rota": "08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG CILINDROS 3o PISO SUL - F",
"turno": "T2",
"rota": "08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG CILINDROS 3o PISO NORTE - M",
"turno": "T2",
"rota": "08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "BANHEIRO ENG CILINDROS 3o PISO NORTE - F",
"turno": "T2",
"rota": "08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "ESCADARIA MEZANINO OESTE",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "ESCADARIA NORTE MEZANINO LESTE",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ESCADARIA SUL MEZANINO LESTE",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - SALA ROCADEIRA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - SALA PODADOR",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - SALA PULVERIZADOR / EAD",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - SALA MOTOPODA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - SALA LAVADORA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - SALA OFICINA DE IDEIAS",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA PROCESSOS - SALA ADM",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA PROCESSOS - SALA REUNIAO I",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P31",
"sala": "BRUNIMENTO - SALA SUPERVISAO",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "BRUNIMENTO - SALA DA COLA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TRF - SALA ADM MEZANINO",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "TRF - SALA DE REUNIAO MEZANINO",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "FUNDICAO - SALA METROLOGIA 3D",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA PROCESSOS - FUNDICAO MAGNESIO",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "PLANEJAMENTO INDUSTRIAL - SALA IMS I",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "PLANEJAMENTO INDUSTRIAL - SALA IMS II",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "PLANEJAMENTO INDUSTRIAL - SALA IMS IV",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "PLANEJAMENTO INDUSTRIAL - SALA IMS III",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA MANUTENCAO - PROJETOS I",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA MANUTENCAO - PROJETOS II",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA MANUTENCAO - SALA ADM",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "SALA TOMOGRAFIA COMPUTADORIZADA",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "SALA DOS TECNICOS MAGNESIO",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "CROMO III - LABORATORIO",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "USINAGEM - SALA RAIO X",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P31",
"sala": "SALA GERENCIA PROJETOS SIMULACAO",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA MANUTENCAO - COPA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA PROCESSOS CILINDROS - COPA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA MANUTENCAO - HALL",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "PLANEJAMENTO INDUSTRIAL - HALL",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P31",
"sala": "ENGENHARIA PROCESSOS - HALL NORTE",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA PROCESSOS - HALL SUL",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - HALL NORTE",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - HALL SUL",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TREINAMENTOS - CORREDOR",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TRF - ADM OFICINA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TRF - OFICINA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P31",
"sala": "ENGENHARIA MANUTENCAO - SALA GERENCIA",
"turno": "T3",
"rota": "07", 
"dom": "X",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P31",
"sala": "TRF - COPA",
"turno": "T3",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P32",
"sala": "BANHEIRO ETE - M",
"turno": "T2",
"rota": "01", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P32",
"sala": "AREA DE LAVAGEM",
"turno": "",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P32",
"sala": "SALA DE CONTROLE",
"turno": "T2",
"rota": "01", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P32",
"sala": "LABORATORIO QUIMICO",
"turno": "T2",
"rota": "01", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P37",
"sala": "PORTARIA 4",
"turno": "T3",
"rota": "04", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P38",
"sala": "BANHEIRO CQT - M",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P38",
"sala": "BANHEIRO CQT - F",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P38",
"sala": "LABORATORIO AUTOMACAO",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P38",
"sala": "ENGENHARIA DE AUTOMACAO",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P42",
"sala": "BANHEIRO PORTARIA 3 - F",
"turno": "T2, T3",
"rota": "09, 08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P42",
"sala": "BANHEIRO PORTARIA 3 - M",
"turno": "T2, T3",
"rota": "09, 08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P42",
"sala": "BANHEIRO PORTARIA 3 - C",
"turno": "T2",
"rota": "09, 08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P42",
"sala": "PORTARIA 3 - SALA DE ESPERA",
"turno": "T2",
"rota": "09, 08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P42",
"sala": "PORTARIA 3 - RECEPCAO",
"turno": "T2",
"rota": "09, 08", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P42",
"sala": "PORTARIA 3 - SALA CLAVICULARIO",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO EXPEDICAO - M",
"turno": "T2, T3",
"rota": "09, 09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO EXPEDICAO - F",
"turno": "T2, T3",
"rota": "09, 09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO EMBALAGEM - F",
"turno": "T2, T3",
"rota": "09, 09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO MOTORISTAS - F",
"turno": "T2, T3",
"rota": "09, 09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO MOTORISTAS - M",
"turno": "T2, T3",
"rota": "09, 09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO RECURSOS HUMANOS 1o PISO - M",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO RECURSOS HUMANOS 1o PISO - F",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO MARKETING 2o PISO - M",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO MARKETING 2o PISO - F",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO VENDAS 2o PISO - M",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO VENDAS 2o PISO - F",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO INFRAESTRUTURA 1o PISO - M",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO INFRAESTRUTURA 1o PISO - F",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "BANHEIRO WRS P43B - M",
"turno": "T2, T3",
"rota": "", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P43",
"sala": "BANHEIRO WRS P43B - F",
"turno": "T2, T3",
"rota": "", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P43",
"sala": "ELEVADOR SOCIAL",
"turno": "T3",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "ESCADARIAS OESTE INFRA / RH / MVV",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "ESCADARIAS LESTE INFRA / RH / MVV",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "HALL DE ENTRADA",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "EXPEDICAO - SALA ADM",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "EXPEDICAO - SALA DE REUNIAO I",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "EXPEDICAO - COPA",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "RH - SALA ADM",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MVV - HALL DE ENTRADA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "RH - SALA DIRETORIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "RH - HALL DE ENTRADA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "RH - SALA REUNIAO I",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "RH - SALA GERENCIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "MVV - SALA VICE PRESIDENCIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MVV - SALA SECRETARIA VP",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MKT - SALA REUNIAO II",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "VLD - SALA POS-VENDAS",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "RH - COPA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "EXPEDICAO - SALA DE ESPERA TRANSP.",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "RH - SALA DINAMICA I",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "RH - SALA VIDEOCONFERENCIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "UIE - SALA REUNIAO I",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "UIE - SALA GERENCIA INFRAESTRUTURA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "ASM - SALA GERENCIA SEGURANCA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "UIE - SALA REUNIAO IV",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "UIE - SALA ADM",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "MVV - SALA REUNIAO II",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MVV - SALA REUNIAO I",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "VLD - SALA GERENCIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "VLD - SALA GERENCIAS REGIONAIS",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MKT - SALA REUNIAO I",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MVV - SALA ADM",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "UIE - COPA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "MVV - COPA I",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MVV - COPA II",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MQC - SALA GERENCIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MKT - SALA GERENCIA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "UIE - SALA ARQUIVO",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "EXPEDICAO - HALL DE ENTRADA",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "EXPEDICAO - AREA DE LAZER",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "UIE - AREA DE LAZER",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "RH / UIE - CORREDOR",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "SALA EMPRESTIMO DE MAQUINAS",
"turno": "T2",
"rota": "09", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "VLD - SALA POS-VENDAS DEPOSITO",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "MVV - SALA VENDAS AMERICA LATINA",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P43",
"sala": "RH - SALA DEPOSITO",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P43",
"sala": "VLD - SALA DEPOSITO",
"turno": "T3",
"rota": "12", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "BANHEIRO VESTIARIO TERREO - M",
"turno": "T2, T3",
"rota": "10, 07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "BANHEIRO VESTIARIO ZPT 2o ANDAR - F",
"turno": "T2, T3",
"rota": "10, 07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "BANHEIRO ZPT 2o ANDAR - M",
"turno": "T2, T3",
"rota": "10, 07", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "BANHEIRO ENG PRODUTO 4o ANDAR - F",
"turno": "T2, T3",
"rota": "10, 13", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "BANHEIRO ENG PRODUTO 4o ANDAR - C",
"turno": "T2, T3",
"rota": "10, 13", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "BANHEIRO ENG PRODUTO 4o ANDAR - M",
"turno": "T2, T3",
"rota": "10, 13", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "ELEVADOR SOCIAL",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P49",
"sala": "ESCADARIA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P49",
"sala": "TERREO - HALL DE ENTRADA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "TERREO - OFICINA TESTE DINAMICO E CAMPO",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "TERREO - RECEBIMENTO DE MERCADORIAS",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "1o ANDAR - HALL DE ENTRADA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "2o ANDAR - HALL DE ENTRADA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "2o ANDAR - OFICINA DURABILIDADE E FUNCAO",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "2o ANDAR - SALA REUNIAO 02.01",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P49",
"sala": "2o ANDAR - SALA REUNIAO 02.02",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P49",
"sala": "2o ANDAR - COPA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "3o ANDAR - HALL DE ENTRADA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "3o ANDAR - SALA ADM DTD/DSS",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "4o ANDAR - HALL DE ENTRADA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "4o ANDAR - SALA REUNIAO 04.01",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P49",
"sala": "4o ANDAR - SALA REUNIAO 04.02 VIDEOCONF",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P49",
"sala": "4o ANDAR - SALA REUNIAO 04.03",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P49",
"sala": "4o ANDAR - COPA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "4o ANDAR - ENG PRODUTO - SALA ADM",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "4o ANDAR - ENG PRODUTO - SALA GERENCIA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "5o ANDAR - HALL DE ENTRADA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "5o ANDAR - SALA GERENCIA",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "5o ANDAR - SALA ADM",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P49",
"sala": "4o ANDAR - SALA VP OPERACOES",
"turno": "T2",
"rota": "10", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": "X"
}, 
{
"predio": "P50",
"sala": "BANHEIRO MONTAGEM - M",
"turno": "T1, T2, T3",
"rota": "03, 04, 03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MONTAGEM - F",
"turno": "T1, T2, T3",
"rota": "03, 04, 03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MONTAGEM - C",
"turno": "T1, T2, T3",
"rota": "03, 04, 03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO PINTURA - M",
"turno": "T1, T2, T3",
"rota": "03, 04, 03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO PINTURA - F",
"turno": "T1, T2, T3",
"rota": "03, 04, 03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MEZANINO OESTE - M",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MEZANINO OESTE - F",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MEZANINO OESTE - C",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MEZANINO LESTE - M",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "BANHEIRO MEZANINO LESTE - F",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ELEVADOR",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ESCADARIA 01",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ESCADARIA 02",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ENTRADA PRINCIPAL",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "AUDITORIA DE PRODUTO",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "AUDITORIA DE PRODUTO - COPA",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DOS TECNICOS",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DOS TECNICOS - COPA",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DOS TECNICOS - REUNIAO 01",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DOS TECNICOS - REUNIAO 02",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "TRF",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE ETIQUETAS",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE TREINAMENTO",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "METROLOGIA",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SUPERVISAO",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SUPERVISAO - COPA",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SUPERVISAO - REUNIAO 01",
"turno": "T3",
"rota": "03", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "LABORATORIO VIRABREQUIM",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "LABORATORIO POLIMEROS",
"turno": "T3",
"rota": "03", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "HALL MEZANINO",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "AREA DE ESTAR 01",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "COPA 01",
"turno": "T2, T3",
"rota": "04, 15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE ENCONTRO 01",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE ENCONTRO 02",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE TREINAMENTO",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE ARQUIVO 01",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA GERENTE 01",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA GERENTE 02",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA GERENTE 03",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA GERENTE 04",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA VICE PRESIDENTE 01",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA VICE PRESIDENTE 02",
"turno": "T2",
"rota": "05, 15", 
"dom": "",
"seg": "",
"ter": "X",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE REUNIAO 01",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ENGENHARIA DE PROCESSOS DE MOTORES",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE REUNIAO 02",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE REUNIAO 03",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "AREA DE DESCANSO",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ZEF",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "ENGENHARIA DE CILINDROS - PROJETISTAS",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DIRETOR LOGÍSTICA",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "QUALIDADE",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE REUNIAO 04",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "AREA DE ESTAR 02",
"turno": "T3",
"rota": "15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "COPA 02",
"turno": "T3",
"rota": "04, 15", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE ENCONTRO 03",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P50",
"sala": "SALA DE ENCONTRO 04",
"turno": "T3",
"rota": "15", 
"dom": "X",
"seg": "",
"ter": "",
"qua": "",
"qui": "",
"sex": "",
"sab": ""
}, 
{
"predio": "P52",
"sala": "BANHEIRO TERREO - M",
"turno": "T1, T2, T3",
"rota": "07, 14", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P52",
"sala": "BANHEIRO TERREO - F / PNE",
"turno": "T1, T2, T3",
"rota": "07, 14", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P52",
"sala": "BANHEIRO MEZANINO - M",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "BANHEIRO MEZANINO - F",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "COPA MEZANINO",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "HALL DE ENTRADA",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA CAM - PROCESSOS",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA SUPERVISAO",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA CAM - SUPORTE",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA DE OPERACOES",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "HALL QUALIDADE",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA QUALIDADE",
"turno": "T2",
"rota": "07", 
"dom": "",
"seg": "X",
"ter": "",
"qua": "X",
"qui": "",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "HALL MEZANINO",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA DE REUNIAO 01 - MEZANINO",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P52",
"sala": "ENGENHARIA DE FERRAMENTARIA",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA GERENTE",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA DE REUNIAO 02 - MEZANINO",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P52",
"sala": "PROJETOS FERRAMENTARIA",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P52",
"sala": "SALA DE REUNIAO 03 - MEZANINO",
"turno": "T3",
"rota": "14", 
"dom": "X",
"seg": "",
"ter": "X",
"qua": "",
"qui": "X",
"sex": "",
"sab": ""
}, 
{
"predio": "P56",
"sala": "BANHEIRO HALL TERREO - PNE",
"turno": "T2,T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "BANHEIRO AMBULATORIO - M / PNE",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "BANHEIRO AMBULATORIO - F / PNE",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "BANHEIRO CONVIVIO - M",
"turno": "T1, T2, T3",
"rota": "05, 11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "BANHEIRO CONVIVIO - F / PNE",
"turno": "T1, T2, T3",
"rota": "05, 11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO RESTAURANTE - M",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO RESTAURANTE - F",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO CAMPO - M",
"turno": "T2",
"rota": "05", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO CAMPO - F",
"turno": "T2",
"rota": "05", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO 2o PAVIMENTO - M",
"turno": "T1, T2, T3",
"rota": "05, 12, 11", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO 3o PAVIMENTO - F",
"turno": "T2,T3",
"rota": "13, 08", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "VESTIARIO 3o PAVIMENTO - M",
"turno": "T1, T2, T3",
"rota": "05, 12, 11", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - COPA",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "ELEVADOR SOCIAL - VESTIARIO",
"turno": "T2",
"rota": "", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "ESCADARIA VESTIARIOS",
"turno": "T2, T3",
"rota": "13, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "HALL DE ENTRADA - TERREO",
"turno": "T2,T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA DE ESPERA",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA NQV I",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA DE AMAMENTACAO",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA NQV II",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA DE TRIAGEM",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA CONSULTORIO II",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA CONSULTORIO III",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA LABORATORIO POSTURAL",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA PROGRAMA CUIDAR",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA GESTAO E SAUDE",
"turno": "T2",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AMBULATORIO - SALA CONSULTORIO I",
"turno": "T2, T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "AREA DE CONVIVIO",
"turno": "T2,T3",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "PROVADOR",
"turno": "T2",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "SALA RENOVA",
"turno": "T2",
"rota": "11, 10", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "1o PAVIMENTO - HALL",
"turno": "T2,T3",
"rota": "05, 12, 11", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P56",
"sala": "2o PAVIMENTO - HALL",
"turno": "T2,T3",
"rota": "05, 13, 08", 
"dom": "X",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": ""
}, 
{
"predio": "P15",
"sala": "ONE STIHL - SALA ADM",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - SALA DE REUNIAO 01",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - SALA DE REUNIAO 02",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - SALA DE REUNIAO 03",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - SALA DE REUNIAO 04",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - HALL DE ENTRADA",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - LABORATORIO",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - SALA DIRETOR",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - GREEN ROOM",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - BLUE ROOM",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - RED ROOM",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}, 
{
"predio": "P15",
"sala": "ONE STIHL - COPA",
"turno": "T3",
"rota": "17", 
"dom": "",
"seg": "X",
"ter": "X",
"qua": "X",
"qui": "X",
"sex": "X",
"sab": "X"
}];
